import express, { Request, Response, NextFunction } from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import path from 'path';
import rateLimit from 'express-rate-limit';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import crypto from 'crypto';

// Load environment variables
dotenv.config();

import authRoutes from './routes/authRoutes';
import courseRoutes from './routes/courseRoutes';
import dashboardRoutes from './routes/dashboardRoutes';
import paymentRoutes from './routes/paymentRoutes';
import supportRoutes from './routes/supportRoutes';
import { handleStripeWebhook } from './controllers/paymentController';
import prisma from './config/db';

const app = express();
const PORT = process.env.PORT || 5000;

// ✅ Trust Railway/Vercel reverse proxy (fixes X-Forwarded-For error with rate-limit)
app.set('trust proxy', 1);

// ✅ 0. SECURITY: Check for Critical Environment Variables
if (!process.env.JWT_SECRET) {
  console.error('FATAL ERROR: JWT_SECRET is not defined in environment variables.');
  console.error('The server cannot start without a secure JWT_SECRET.');
  process.exit(1);
}

// ✅ 1. SECURITY: Helmet Headers (في الأول دائماً)
app.use(helmet({
  hsts: { maxAge: 31536000, includeSubDomains: true, preload: true },
  contentSecurityPolicy: {
    directives: {
      defaultSrc:  ["'self'"],
      scriptSrc:   ["'self'"],
      styleSrc:    ["'self'", "'unsafe-inline'"],
      imgSrc:      ["'self'", 'data:', 'https:', 'https://res.cloudinary.com'],
      // ✅ السماح بتضمين فيديوهات YouTube و Bunny.net و Cloudinary PDFs
      frameSrc:    ["'self'", 'https://www.youtube.com', 'https://www.youtube-nocookie.com', 'https://*.mediadelivery.net', 'https://*.b-cdn.net', 'https://res.cloudinary.com'],
      childSrc:    ["'self'", 'https://www.youtube.com', 'https://www.youtube-nocookie.com', 'https://*.mediadelivery.net', 'https://*.b-cdn.net', 'https://res.cloudinary.com'],
      mediaSrc:    ["'self'", 'https://www.youtube.com', 'https://www.youtube-nocookie.com', 'https://*.mediadelivery.net', 'https://*.b-cdn.net', 'blob:', 'data:'],
      connectSrc:  ["'self'", 'https://www.youtube.com', 'https://www.youtube-nocookie.com', 'https://*.mediadelivery.net', 'https://*.b-cdn.net', 'https://api.cloudinary.com'],
    }
  },
  // ✅ Using frameguard: { action: 'deny' } to satisfy X-Frame-Options: deny
  frameguard: { action: 'deny' },
  noSniff: true,
  xssFilter: true
}));

// ✅ إعدادات الـ CORS للسماح بالفرونت إند الخاص بك فقط
app.use(
  cors({
    origin: [
      'https://portofa.vercel.app', 
      'https://portofa-git-main-emelnasr-1066s-projects.vercel.app', 
      'http://localhost:5173'
    ], // إضافة رابط الموقع الأساسي، ورابط Vercel الفرعي، و localhost للوقت التطوير
    methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
    allowedHeaders: ['Content-Type', 'Authorization', 'Origin', 'Accept', 'X-Visitor-Id'],
    credentials: true, // مهم جداً لدعم الكوكيز وإرسال الـ Headers
    optionsSuccessStatus: 200
  })
);

// ✅ 2.5 Stripe Webhook (MUST be before express.json() to keep raw body)
app.post('/api/payments/stripe-webhook', express.raw({ type: 'application/json' }), handleStripeWebhook);

// ✅ 3. Body Parsers & Cookies (خط الدفاع الأول لقراءة البيانات والكوكيز)
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true, limit: '10mb' }));
app.use(cookieParser());

// ✅ 4. Rate Limiters (دلوقتي يقدروا يقروا الطلبات بأمان ومن غير أخطاء)
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100, 
  message: 'Too many requests from this IP, please try again later.'
});

const authLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, 
  max: 10, 
  message: 'Too many authentication attempts, please try again later.',
  skipSuccessfulRequests: true
});

// تطبيق الـ Global Limiter
app.use(limiter);

// Static route for uploads
app.use('/uploads', express.static(path.join(__dirname, '../../uploads')));

// ✅ Visitor Tracking Middleware (Header-based for accurate tracking, fixes race condition)
app.use(async (req: Request, res: Response, next: NextFunction) => {
  if (req.path.startsWith('/api') && req.path !== '/health') {
    // Read the unique visitor ID generated by the frontend's localStorage
    const visitorId = req.headers['x-visitor-id'] as string | undefined;

    if (visitorId) {
      const ip = req.headers['x-forwarded-for']?.toString().split(',')[0].trim() || req.socket.remoteAddress || 'unknown';
      const userAgent = req.headers['user-agent'] || 'unknown';

      // Save new visitor to DB - upsert ensures no duplicates
      prisma.visitor.upsert({
        where: { visitorId },
        update: {},
        create: { visitorId, ip, userAgent }
      }).catch(() => {}); // silently catch
    }
  }
  next();
});

// Health check endpoint
app.get('/health', (req: Request, res: Response) => {
  res.status(200).json({ status: 'ok', message: 'Cinematic Edu API is running' });
});

// ✅ 5. API Routes (بعد التأكد من ترتيب كل الـ Middlewares)
app.use('/api/auth/register', authLimiter); 
app.use('/api/auth/login', authLimiter);    
app.use('/api/auth', authRoutes);
app.use('/api/courses', courseRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/payments', paymentRoutes);
app.use('/api/support', supportRoutes);

// Error-handling middleware
app.use((err: Error, req: Request, res: Response, next: NextFunction) => {
  console.error('Unhandled Error:', err.message);
  res.status(500).json({
    message: 'Something went wrong on the server',
    error: process.env.NODE_ENV === 'development' ? err.message : undefined
  });
});

// Start Server
app.listen(PORT, () => {
  console.log(`========================================`);
  console.log(`Server is running on http://localhost:${PORT}`);
  console.log(`Health Check: http://localhost:${PORT}/health`);
  console.log(`========================================`);
});